spring.application.name=videoResize
spring.config.import=optional:file:env.properties
spring.datasource.url=${KY_URL}
server.port=3005
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# cloudflare
cloudflare.key.id=${CLOUDFLARE_KEY_ID}
cloudflare.app.key=${CLOUDFLARE_APP_KEY}
cloudflare.endpoint=${CLOUDFLARE_ENDPOINT}
cloudflare.region=${CLOUDFLARE_REGION}
cloudflare.bucket-raw=post-raw
cloudflare.bucket-processed=post-processed
cloudflare.public.url=https://pub-2041952f2a4b4563885e7dcacd123bdf.r2.dev
cloudflare.raw.url=https://pub-854c3b82595b453b97711ef3bc2bd2ca.r2.dev
